import "./globals.css";
import Nav from "./components/Nav";
import { getServerSession } from "next-auth/next";
import { options } from "@/lib/auth";
import { NextAuthProvider } from "./providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  //Fetch user so we can access the data wherever.
  const session = await getServerSession(options);
  return (
    <html lang="en">
      <body>
        <Nav user={session?.user} expires={session?.expires as string} />
        <NextAuthProvider>{children}</NextAuthProvider>
      </body>
    </html>
  );
}
